// <auto-generated />
using System;
using AviaCompany.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AviaCompany.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(AviaCompanyDbContext))]
    [Migration("20251217065556_FixTableNamesToSnakeCase")]
    partial class FixTableNamesToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AviaCompany.Domain.Models.Aircrafts.AircraftFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("aircraft_families");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Airbus",
                            Name = "A320"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Boeing",
                            Name = "737"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Sukhoi",
                            Name = "Superjet 100"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Irkut",
                            Name = "MS-21"
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Bombardier",
                            Name = "CRJ"
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Airbus",
                            Name = "A330"
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "Boeing",
                            Name = "777"
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "Airbus",
                            Name = "A350"
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "Boeing",
                            Name = "787"
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "Embraer",
                            Name = "Embraer E-Jet"
                        });
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Aircrafts.AircraftModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CargoCapacity")
                        .HasColumnType("double")
                        .HasColumnName("cargo_capacity");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int")
                        .HasColumnName("family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int")
                        .HasColumnName("passenger_capacity");

                    b.Property<double>("Range")
                        .HasColumnType("double")
                        .HasColumnName("range");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_aircraft_models_family_id");

                    b.ToTable("aircraft_models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoCapacity = 20000.0,
                            FamilyId = 1,
                            Name = "A320-200",
                            PassengerCapacity = 180,
                            Range = 6100.0
                        },
                        new
                        {
                            Id = 2,
                            CargoCapacity = 25000.0,
                            FamilyId = 1,
                            Name = "A321neo",
                            PassengerCapacity = 240,
                            Range = 7400.0
                        },
                        new
                        {
                            Id = 3,
                            CargoCapacity = 22000.0,
                            FamilyId = 2,
                            Name = "737-800",
                            PassengerCapacity = 189,
                            Range = 5765.0
                        },
                        new
                        {
                            Id = 4,
                            CargoCapacity = 23000.0,
                            FamilyId = 2,
                            Name = "737 MAX 8",
                            PassengerCapacity = 210,
                            Range = 6570.0
                        },
                        new
                        {
                            Id = 5,
                            CargoCapacity = 12000.0,
                            FamilyId = 3,
                            Name = "SSJ-100",
                            PassengerCapacity = 98,
                            Range = 3048.0
                        },
                        new
                        {
                            Id = 6,
                            CargoCapacity = 24000.0,
                            FamilyId = 4,
                            Name = "MS-21-300",
                            PassengerCapacity = 211,
                            Range = 6000.0
                        },
                        new
                        {
                            Id = 7,
                            CargoCapacity = 8000.0,
                            FamilyId = 5,
                            Name = "CRJ-200",
                            PassengerCapacity = 50,
                            Range = 3045.0
                        },
                        new
                        {
                            Id = 8,
                            CargoCapacity = 18000.0,
                            FamilyId = 1,
                            Name = "A319",
                            PassengerCapacity = 160,
                            Range = 6850.0
                        },
                        new
                        {
                            Id = 9,
                            CargoCapacity = 19000.0,
                            FamilyId = 2,
                            Name = "737-700",
                            PassengerCapacity = 149,
                            Range = 6230.0
                        },
                        new
                        {
                            Id = 10,
                            CargoCapacity = 15000.0,
                            FamilyId = 5,
                            Name = "CRJ-900",
                            PassengerCapacity = 90,
                            Range = 3400.0
                        });
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Flights.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftModelId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_model_id");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("arrival_city");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrival_date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("departure_city");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("departure_date");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("departure_time");

                    b.Property<TimeSpan>("FlightDuration")
                        .HasColumnType("time(6)")
                        .HasColumnName("flight_duration");

                    b.HasKey("Id");

                    b.HasIndex("AircraftModelId")
                        .HasDatabaseName("ix_flights_aircraft_model_id");

                    b.ToTable("flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftModelId = 1,
                            ArrivalCity = "Санкт-Петербург",
                            ArrivalDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1001",
                            DepartureCity = "Москва",
                            DepartureDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 8, 0, 0, 0),
                            FlightDuration = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            AircraftModelId = 2,
                            ArrivalCity = "Сочи",
                            ArrivalDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1002",
                            DepartureCity = "Москва",
                            DepartureDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 10, 30, 0, 0),
                            FlightDuration = new TimeSpan(0, 2, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            AircraftModelId = 3,
                            ArrivalCity = "Екатеринбург",
                            ArrivalDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1003",
                            DepartureCity = "Москва",
                            DepartureDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            FlightDuration = new TimeSpan(0, 2, 15, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            AircraftModelId = 4,
                            ArrivalCity = "Новосибирск",
                            ArrivalDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1004",
                            DepartureCity = "Москва",
                            DepartureDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 14, 30, 0, 0),
                            FlightDuration = new TimeSpan(0, 4, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            AircraftModelId = 6,
                            ArrivalCity = "Владивосток",
                            ArrivalDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1005",
                            DepartureCity = "Москва",
                            DepartureDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 16, 0, 0, 0),
                            FlightDuration = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            AircraftModelId = 1,
                            ArrivalCity = "Москва",
                            ArrivalDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1006",
                            DepartureCity = "Санкт-Петербург",
                            DepartureDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 19, 0, 0, 0),
                            FlightDuration = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            AircraftModelId = 5,
                            ArrivalCity = "Сочи",
                            ArrivalDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1007",
                            DepartureCity = "Санкт-Петербург",
                            DepartureDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 9, 0, 0, 0),
                            FlightDuration = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            AircraftModelId = 2,
                            ArrivalCity = "Москва",
                            ArrivalDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1008",
                            DepartureCity = "Сочи",
                            DepartureDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 20, 0, 0, 0),
                            FlightDuration = new TimeSpan(0, 2, 30, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            AircraftModelId = 3,
                            ArrivalCity = "Москва",
                            ArrivalDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1009",
                            DepartureCity = "Екатеринбург",
                            DepartureDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 7, 30, 0, 0),
                            FlightDuration = new TimeSpan(0, 2, 15, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            AircraftModelId = 7,
                            ArrivalCity = "Санкт-Петербург",
                            ArrivalDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU1010",
                            DepartureCity = "Новосибирск",
                            DepartureDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 11, 0, 0, 0),
                            FlightDuration = new TimeSpan(0, 4, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Passengers.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("passport_number");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Иванов Иван Иванович",
                            PassportNumber = "45 01 123456"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Петров Петр Петрович",
                            PassportNumber = "45 02 234567"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Сидорова Анна Владимировна",
                            PassportNumber = "45 03 345678"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Козлов Дмитрий Сергеевич",
                            PassportNumber = "45 04 456789"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1987, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Николаева Екатерина Андреевна",
                            PassportNumber = "45 05 567890"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1995, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Федоров Алексей Викторович",
                            PassportNumber = "45 06 678901"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1991, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Морозова Ольга Дмитриевна",
                            PassportNumber = "45 07 789012"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1983, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Волков Сергей Иванович",
                            PassportNumber = "45 08 890123"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1993, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Павлова Мария Петровна",
                            PassportNumber = "45 09 901234"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1989, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Семенов Андрей Николаевич",
                            PassportNumber = "45 10 012345"
                        });
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Tickets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<bool>("HasHandLuggage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_hand_luggage");

                    b.Property<decimal?>("LuggageWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("luggage_weight");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("seat_number");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .HasDatabaseName("ix_tickets_flight_id");

                    b.HasIndex("PassengerId")
                        .HasDatabaseName("ix_tickets_passenger_id");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            HasHandLuggage = true,
                            LuggageWeight = 15.5m,
                            PassengerId = 1,
                            SeatNumber = "10A"
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            HasHandLuggage = true,
                            LuggageWeight = 10.0m,
                            PassengerId = 2,
                            SeatNumber = "10B"
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            HasHandLuggage = false,
                            LuggageWeight = 0m,
                            PassengerId = 3,
                            SeatNumber = "11A"
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            HasHandLuggage = true,
                            LuggageWeight = 8.0m,
                            PassengerId = 4,
                            SeatNumber = "11B"
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 1,
                            HasHandLuggage = true,
                            LuggageWeight = 0m,
                            PassengerId = 5,
                            SeatNumber = "12A"
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 1,
                            HasHandLuggage = true,
                            LuggageWeight = 12.0m,
                            PassengerId = 6,
                            SeatNumber = "12B"
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 1,
                            HasHandLuggage = false,
                            LuggageWeight = 0m,
                            PassengerId = 7,
                            SeatNumber = "13A"
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 1,
                            HasHandLuggage = true,
                            LuggageWeight = 9.5m,
                            PassengerId = 8,
                            SeatNumber = "13B"
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 2,
                            HasHandLuggage = true,
                            LuggageWeight = 20.0m,
                            PassengerId = 9,
                            SeatNumber = "15C"
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 2,
                            HasHandLuggage = true,
                            LuggageWeight = 12.5m,
                            PassengerId = 10,
                            SeatNumber = "15D"
                        });
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Aircrafts.AircraftModel", b =>
                {
                    b.HasOne("AviaCompany.Domain.Models.Aircrafts.AircraftFamily", "Family")
                        .WithMany("Models")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aircraft_models_family_id_aircraft_families");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Flights.Flight", b =>
                {
                    b.HasOne("AviaCompany.Domain.Models.Aircrafts.AircraftModel", "AircraftModel")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flights_aircraft_model_id_aircraft_models");

                    b.Navigation("AircraftModel");
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Tickets.Ticket", b =>
                {
                    b.HasOne("AviaCompany.Domain.Models.Flights.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_flight_id_flights");

                    b.HasOne("AviaCompany.Domain.Models.Passengers.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_passenger_id_passengers");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Aircrafts.AircraftFamily", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Aircrafts.AircraftModel", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Flights.Flight", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AviaCompany.Domain.Models.Passengers.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
