name: AviaCompany Domain Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore AviaCompany/AviaCompany.sln
      
    - name: Build
      run: dotnet build AviaCompany/AviaCompany.sln --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test AviaCompany/AviaCompany.Tests/AviaCompany.Tests.csproj --no-build --verbosity normal --configuration Release